#!/bin/sh -e

#
# Init
# ====
#

#
# Print all arguments in yellow.
#
pc() {
    echo -e "\033[1;33m$@\033[0m"
}

#
# Call `pc` and execute command with arguments.
#
# This will print `touch test` in yellow and touch the file `test`.
#
#     p touch test
#
p() {
    pc "$@"
    "$@"
}

#
# Like `pc` but skip a line before and after command execution.
#
pl() {
    pc "$@"
    echo
    "$@"
    echo
}

p mkdir tox
TOXDIR=$(pwd)/tox

#
# `libsodium`
# ===========
#

p cd "$TOXDIR"
pl git clone https://github.com/jedisct1/libsodium.git
p cd libsodium

pl ./autogen.sh
pl ./configure
pl make
pl make install DESTDIR="$TOXDIR"

#
# `toxcore`
# =========
#

p cd "$TOXDIR"
pl git clone https://github.com/irungentoo/toxcore.git
p cd toxcore

pl ./autogen.sh

pl ./configure \
    --with-libsodium-headers="$TOXDIR/usr/local/include" \
    --with-libsodium-libs="$TOXDIR/usr/local/lib"

pl make
pl make install DESTDIR="$TOXDIR"

#
# Toxic
# =====
#

p cd "$TOXDIR"
pl git clone https://github.com/Tox/toxic.git
p cd toxic/build

#
# Libraries needed by the software. Normally the makefile add them if
# it can find the globally-installed libraries, but we need to set them
# manually for a local installation.
#
TOXIC_LDLIBS='-lncursesw -ltoxcore -ltoxdns'

#
# Actually the makefile will use `pkg-config $(LIBS)` to figure which
# flags to give to the linker. This won't work for a local install.
#
# I used to remove the library check code in the makefile, but I found this
# hack that don't require to alter the makefile; by overriding `LIBS` to
# contain `--version`, the command will be `pkg-config --version` which will
# not return an error code (so the makefile will think all libs were found).
#
# After, it is used like this `pkg-config --cflags $(LIBS)`, so
# `pkg-config --cflags --version`. The command will fail and leave an
# empty standard output (so nothing will be added to `CFLAGS` nor `LDFLAGS`.
#
TOXIC_LIBS='--version'

pl make \
    LIBS="$TOXIC_LIBS" \
    USER_CFLAGS="-I$TOXDIR/usr/local/include" \
    USER_LDFLAGS="-L$TOXDIR/usr/local/lib $TOXIC_LDLIBS"

#
# End
# ===
#

echo -e '\033[32mSeems everything went successfully!\033[0m'
echo
echo 'You should add this to your profile for the software to work:'
echo
echo "    export LD_LIBRARY_PATH=\"$TOXDIR/usr/local/lib:\$LD_LIBRARY_PATH\""
echo
echo '... or use the helper script in the readme to launch `toxic`.'
